export {default as Loader } from './Loader';
export {default as LoaderBlock } from './LoaderBlock';
export {default as Navbar } from './Navbar';
export {default as Footer } from './Footer';
export {default as Welcome } from './Welcome';
export {default as About } from './About';
export {default as Contact} from './Contact';
export {default as Login} from './login/Login';
export {default as FAQ} from './FAQ';
export {default as Chevron} from './Chevron';
export {default as FAQCall} from './FAQCall';
export {default as Dashboard} from './Dashboard';
export {default as Sidebar} from './Sidebar';
export {default as Admins} from './Admins';
export {default as Register} from './Register';
export {default as CreatePoll} from './createPoll/CreatePoll';
export {default as Users} from './Users';
export {default as Profile} from './Profile';
export {default as AdminLogin} from './AdminLogin';
export {default as AdminRegister} from './AdminRegister';
export {default as Analytics} from './Analytics';
export {default as ContactAdmin} from './ContactAdmin';
export {default as AdminView} from './AdminView';
export {default as ManageAdmins} from './ManageAdmins';
export {default as SinglePoll} from './SinglePoll';
export {default as Reports} from './Reports';
export {default as Explore} from './Explore';
export {default as NotificationProvider} from './Notifications/NotificationProvider';
export {default as Notify } from './Notify';
export {default as Datedefault } from './Datedefault';
export {default as ActivePoll } from './ActivePoll';
export {default as Forgot } from './Forgot';
